CREATE DATABASE IF NOT EXISTS hopout;
USE hopout;

CREATE TABLE IF NOT EXISTS hopout_characters (
    id INT AUTO_INCREMENT PRIMARY KEY,
    identifier VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    model INT NOT NULL,
    coins INT NOT NULL DEFAULT 1000,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);